apiVersion: apps/v1 # especifica la verion de la api de kubernetes
kind: Deployment # tipo de objeto
metadata:
  name: tower-defense-deployment # nombre del objeto
spec: # especificaciones del objeto
  replicas: 1
  selector:
    matchLabels:
      app: tower-defense-game
  template:
    metadata:
      labels:
        app: tower-defense-game
    spec:
      containers:
      - name: tower-defense-game
        image: luisjhonatan/tower-defense-game:1
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
